name: Test Secrets 2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 直接打印环境变量
        env:
          A: ${{ secrets.A }}
          B: ${{ secrets.B }}
          C: ${{ secrets.C }}
        run: |
          echo "A 长度: ${#A}"
          echo "B 长度: ${#B}"
          echo "C 长度: ${#C}"
          echo "A 第一个字符: ${A:0:1}"
