name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Test
        env:
          MORALIS_KEY: ${{ secrets.MORALIS_KEY }}
          WECHAT_URL: ${{ secrets.WECHAT_URL }}
        run: python test.py
